<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="85993" started-at="2019-01-28T16:08:47Z" finished-at="2019-01-28T16:10:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="85993" started-at="2019-01-28T16:08:47Z" finished-at="2019-01-28T16:10:13Z">
      <class name="com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile">
        <test-method status="PASS" signature="run(org.testng.ITestContext)[pri:0, instance:com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile@6f4a47c7]" name="run" is-config="true" duration-ms="450" started-at="2019-01-28T11:08:46Z" finished-at="2019-01-28T11:08:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@23c650a3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="PASS" signature="startup(java.lang.reflect.Method)[pri:0, instance:com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile@6f4a47c7]" name="startup" is-config="true" duration-ms="63" started-at="2019-01-28T11:08:47Z" finished-at="2019-01-28T11:08:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile.BloodGlucoseOnProfile(java.util.Hashtable) throws java.lang.InterruptedException,java.text.ParseException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="FAIL" signature="BloodGlucoseOnProfile(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile@6f4a47c7]" name="BloodGlucoseOnProfile" duration-ms="79032" started-at="2019-01-28T11:08:47Z" data-provider="getDataBGProfile" finished-at="2019-01-28T11:10:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Date=Current, BGLevel=15.00, Password=Test@123, Time=Current, Runmode=Y, UserName=neil@peter.com, Description=Verify that, system updates BG values on Profile page, TCID=TC09}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Feild Does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Feild Does not exist
	at org.testng.Assert.fail(Assert.java:94)
	at com.qa.meschino.basepages.BasePage.reportFailure(BasePage.java:160)
	at com.qa.meschino.basepages.BasePage.getProfileData(BasePage.java:339)
	at com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile.BloodGlucoseOnProfile(VerifyBloodGlucoseOnProfile.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BloodGlucoseOnProfile -->
        <test-method status="PASS" signature="endTest(org.testng.ITestResult)[pri:0, instance:com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile@6f4a47c7]" name="endTest" is-config="true" duration-ms="6503" started-at="2019-01-28T11:10:06Z" finished-at="2019-01-28T11:10:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=BloodGlucoseOnProfile status=FAILURE method=VerifyBloodGlucoseOnProfile.BloodGlucoseOnProfile(java.util.Hashtable)[pri:0, instance:com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile@6f4a47c7] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.qa.meschino.testcases.BloodGlucoseTracker.VerifyBloodGlucoseOnProfile -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
