<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-A6435CM" name="Login" tests="2" failures="1" timestamp="22 Jan 2019 01:25:46 GMT" time="35.014" errors="0">
  <testcase name="LoginTest" time="33.803" classname="com.qa.meschino.testcases.Login.verifyLogin">
    <failure type="java.lang.AssertionError" message="Verify that, system allows to login with valid Credentials">
      <![CDATA[java.lang.AssertionError: Verify that, system allows to login with valid Credentials
	at com.qa.meschino.testcases.basetest.BaseTest.reportFailure(BaseTest.java:79)
	at com.qa.meschino.testcases.Login.verifyLogin.LoginTest(verifyLogin.java:79)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="0.004" classname="com.qa.meschino.testcases.Login.verifyLogin">
    <skipped/>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- Login -->
