<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-A6435CM" name="Login" tests="3" failures="1" timestamp="17 Jan 2019 02:04:48 GMT" time="85.243" errors="0">
  <testcase name="LoginTest" time="8.394" classname="com.qa.meschino.testcases.Login.verifyLogin"/>
  <testcase name="LoginTest" time="22.581" classname="com.qa.meschino.testcases.Login.verifyLogin"/>
  <testcase name="LoginTest" time="23.044" classname="com.qa.meschino.testcases.Login.verifyLogin">
    <failure type="java.lang.AssertionError" message="Verify that, system does not allow to login with Invalid Credentials">
      <![CDATA[java.lang.AssertionError: Verify that, system does not allow to login with Invalid Credentials
	at com.qa.meschino.testcases.basetest.BaseTest.reportFailure(BaseTest.java:68)
	at com.qa.meschino.testcases.Login.verifyLogin.LoginTest(verifyLogin.java:74)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- Login -->
